### ISSUE TITLE
ADD THESE

### ISSUE THREAD

**Issue by m5anksc0des** [Sayandeep1st/Logistic-Map#1]
1) Is the code working? if yes, add a screenshot of the final result or your page in the Readme file.

**Comment by Sayandeep1st** [comment]
![Screenshot_2023-01-02-20-49-20-653_com.miui.gallery.jpg](https://user-images.githubusercontent.com/119342478/210254210-f4f20883-2cf4-4b11-92cd-f5bfd5992fe2.jpg)
